version: '3'
services:
    web:
        build: .
        networks:
            - net_test
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        depends_on:
            - redis
        env_file: .env
    redis:
        image: 'redis:5.0.4-stretch'
        networks:
            - net_test
        ports:
            - '6379:6379'
networks:
  net_test: